import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { 
  BarChart3, 
  Sparkles, 
  Target, 
  TrendingUp, 
  Zap, 
  Shield, 
  Globe, 
  ArrowRight,
  Check,
  Star,
  Building2,
  Users
} from "lucide-react";

interface LandingPageProps {
  onStartTrial: () => void;
  onLogin: () => void;
  trialRemaining: number;
}

export function LandingPage({ onStartTrial, onLogin, trialRemaining }: LandingPageProps) {
  const features = [
    {
      icon: Target,
      title: "Fund Matching AI",
      description: "Our AI analyzes 500+ VC funds to find the perfect match for your startup profile"
    },
    {
      icon: Sparkles,
      title: "Instant Pitch Decks",
      description: "Generate investor-ready pitch decks tailored to each fund's investment thesis"
    },
    {
      icon: TrendingUp,
      title: "Market Intelligence",
      description: "Real-time data on fund activity, portfolio companies, and investment trends"
    },
    {
      icon: Shield,
      title: "Due Diligence Ready",
      description: "Comprehensive analysis with sources and confidence scores"
    },
    {
      icon: Globe,
      title: "Global Coverage",
      description: "Access to VC funds across North America, Europe, Asia, and emerging markets"
    },
    {
      icon: Zap,
      title: "Lightning Fast",
      description: "Get complete analysis in under 30 seconds with our optimized AI pipeline"
    }
  ];

  const testimonials = [
    {
      quote: "Closed our Series A in 3 weeks using pitch decks generated by this tool.",
      author: "Sarah Chen",
      role: "CEO, TechFlow",
      rating: 5
    },
    {
      quote: "The fund matching saved us months of research. Incredible accuracy.",
      author: "Marcus Johnson",
      role: "Founder, DataSync",
      rating: 5
    },
    {
      quote: "Every startup founder needs this in their toolkit.",
      author: "Elena Rodriguez",
      role: "Partner, Horizon Ventures",
      rating: 5
    }
  ];

  const plans = [
    {
      name: "Starter",
      price: "29",
      period: "month",
      description: "For early-stage founders exploring options",
      features: [
        "10 fund analyses per month",
        "Basic pitch deck generation",
        "Email support",
        "Export to Markdown"
      ],
      cta: "Start Free Trial",
      popular: false
    },
    {
      name: "Pro",
      price: "99",
      period: "month",
      description: "For serious founders actively fundraising",
      features: [
        "Unlimited fund analyses",
        "Advanced pitch customization",
        "Priority AI processing",
        "Export to PDF & PPT",
        "Competitor analysis",
        "Slack integration"
      ],
      cta: "Start Free Trial",
      popular: true
    },
    {
      name: "Enterprise",
      price: "Custom",
      period: "",
      description: "For accelerators and VC firms",
      features: [
        "Everything in Pro",
        "Team collaboration",
        "Custom AI training",
        "API access",
        "Dedicated support",
        "White-label option"
      ],
      cta: "Contact Sales",
      popular: false
    }
  ];

  const stats = [
    { value: "2,500+", label: "Funds Analyzed" },
    { value: "50K+", label: "Pitch Decks Generated" },
    { value: "94%", label: "Match Accuracy" },
    { value: "$2.1B", label: "Funding Raised" }
  ];

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="border-b border-border bg-card/50 backdrop-blur-sm sticky top-0 z-50">
        <div className="container max-w-7xl mx-auto px-4 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center">
                <BarChart3 className="w-5 h-5 text-primary" />
              </div>
              <div>
                <h1 className="text-lg font-semibold text-foreground">DealFlow AI</h1>
                <p className="text-xs text-muted-foreground">VC Intelligence Platform</p>
              </div>
            </div>
            <div className="flex items-center gap-3">
              <Button variant="ghost" size="sm" onClick={onLogin}>
                Sign In
              </Button>
              <Button size="sm" onClick={onStartTrial} className="gap-2">
                <Zap className="w-4 h-4" />
                Try Free
              </Button>
            </div>
          </div>
        </div>
      </header>

      {/* Hero Section */}
      <section className="relative overflow-hidden">
        <div className="absolute inset-0 terminal-grid opacity-30" />
        <div className="container max-w-7xl mx-auto px-4 py-20 md:py-32 relative">
          <div className="max-w-4xl mx-auto text-center">
            <Badge variant="outline" className="mb-6 px-4 py-1.5 text-sm border-primary/30 bg-primary/5">
              <Sparkles className="w-3 h-3 mr-2 text-primary" />
              Powered by Advanced AI
            </Badge>
            
            <h1 className="text-4xl md:text-6xl lg:text-7xl font-bold tracking-tight mb-6">
              Find Your Perfect
              <span className="block text-gradient-success mt-2">VC Match</span>
            </h1>
            
            <p className="text-lg md:text-xl text-muted-foreground mb-8 max-w-2xl mx-auto leading-relaxed">
              AI-powered fund analysis and pitch deck generation. 
              Get matched with the right investors and create compelling pitches in seconds.
            </p>

            <div className="flex flex-col sm:flex-row items-center justify-center gap-4 mb-12">
              <Button 
                size="lg" 
                onClick={onStartTrial}
                className="gap-2 px-8 h-12 text-base glow-success"
              >
                Start Free Analysis
                <ArrowRight className="w-4 h-4" />
              </Button>
              <p className="text-sm text-muted-foreground">
                {trialRemaining > 0 ? (
                  <span className="flex items-center gap-2">
                    <span className="status-dot" />
                    {trialRemaining} free analyses remaining
                  </span>
                ) : (
                  "No credit card required"
                )}
              </p>
            </div>

            {/* Stats */}
            <div className="grid grid-cols-2 md:grid-cols-4 gap-6 pt-8 border-t border-border">
              {stats.map((stat, i) => (
                <div key={i} className="text-center">
                  <p className="text-2xl md:text-3xl font-bold text-foreground">{stat.value}</p>
                  <p className="text-sm text-muted-foreground">{stat.label}</p>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* Trusted By */}
      <section className="border-y border-border bg-card/30 py-8">
        <div className="container max-w-7xl mx-auto px-4">
          <p className="text-center text-sm text-muted-foreground mb-6">Trusted by founders at</p>
          <div className="flex flex-wrap items-center justify-center gap-8 md:gap-12 opacity-50">
            {["Y Combinator", "Techstars", "500 Startups", "Sequoia", "a16z", "Founders Fund"].map((name) => (
              <span key={name} className="text-sm font-medium text-foreground/70">{name}</span>
            ))}
          </div>
        </div>
      </section>

      {/* Features */}
      <section className="py-20 md:py-32">
        <div className="container max-w-7xl mx-auto px-4">
          <div className="text-center mb-16">
            <Badge variant="outline" className="mb-4">Features</Badge>
            <h2 className="text-3xl md:text-4xl font-bold mb-4">Everything you need to raise</h2>
            <p className="text-muted-foreground max-w-2xl mx-auto">
              From fund discovery to pitch preparation, we've got you covered.
            </p>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            {features.map((feature, i) => (
              <div 
                key={i}
                className="p-6 rounded-xl bg-card border border-border card-hover"
              >
                <div className="w-12 h-12 rounded-lg bg-primary/10 flex items-center justify-center mb-4">
                  <feature.icon className="w-6 h-6 text-primary" />
                </div>
                <h3 className="text-lg font-semibold mb-2">{feature.title}</h3>
                <p className="text-sm text-muted-foreground leading-relaxed">{feature.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Social Proof */}
      <section className="py-20 bg-card/30 border-y border-border">
        <div className="container max-w-7xl mx-auto px-4">
          <div className="text-center mb-12">
            <h2 className="text-3xl md:text-4xl font-bold mb-4">Loved by founders</h2>
          </div>

          <div className="grid md:grid-cols-3 gap-6 max-w-5xl mx-auto">
            {testimonials.map((testimonial, i) => (
              <div key={i} className="p-6 rounded-xl bg-card border border-border">
                <div className="flex gap-1 mb-4">
                  {[...Array(testimonial.rating)].map((_, j) => (
                    <Star key={j} className="w-4 h-4 fill-primary text-primary" />
                  ))}
                </div>
                <p className="text-foreground mb-4 leading-relaxed">"{testimonial.quote}"</p>
                <div>
                  <p className="font-medium text-sm">{testimonial.author}</p>
                  <p className="text-xs text-muted-foreground">{testimonial.role}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Pricing */}
      <section className="py-20 md:py-32">
        <div className="container max-w-7xl mx-auto px-4">
          <div className="text-center mb-16">
            <Badge variant="outline" className="mb-4">Pricing</Badge>
            <h2 className="text-3xl md:text-4xl font-bold mb-4">Simple, transparent pricing</h2>
            <p className="text-muted-foreground">Start free, upgrade when you're ready.</p>
          </div>

          <div className="grid md:grid-cols-3 gap-6 max-w-5xl mx-auto">
            {plans.map((plan, i) => (
              <div 
                key={i}
                className={`p-6 rounded-xl border ${
                  plan.popular 
                    ? "bg-card border-primary/50 glow-success" 
                    : "bg-card border-border"
                } relative`}
              >
                {plan.popular && (
                  <Badge className="absolute -top-3 left-1/2 -translate-x-1/2 bg-primary text-primary-foreground">
                    Most Popular
                  </Badge>
                )}
                <div className="mb-6">
                  <h3 className="text-xl font-bold mb-2">{plan.name}</h3>
                  <p className="text-sm text-muted-foreground mb-4">{plan.description}</p>
                  <div className="flex items-baseline gap-1">
                    {plan.price !== "Custom" && <span className="text-sm text-muted-foreground">$</span>}
                    <span className="text-4xl font-bold">{plan.price}</span>
                    {plan.period && <span className="text-muted-foreground">/{plan.period}</span>}
                  </div>
                </div>
                <ul className="space-y-3 mb-6">
                  {plan.features.map((feature, j) => (
                    <li key={j} className="flex items-center gap-2 text-sm">
                      <Check className="w-4 h-4 text-primary flex-shrink-0" />
                      {feature}
                    </li>
                  ))}
                </ul>
                <Button 
                  className="w-full" 
                  variant={plan.popular ? "default" : "outline"}
                  onClick={onStartTrial}
                >
                  {plan.cta}
                </Button>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-20 bg-card/50 border-t border-border">
        <div className="container max-w-4xl mx-auto px-4 text-center">
          <h2 className="text-3xl md:text-4xl font-bold mb-4">Ready to find your perfect investor?</h2>
          <p className="text-muted-foreground mb-8 max-w-xl mx-auto">
            Join thousands of founders using AI to accelerate their fundraising journey.
          </p>
          <Button size="lg" onClick={onStartTrial} className="gap-2 px-8">
            Start Free Analysis
            <ArrowRight className="w-4 h-4" />
          </Button>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-border bg-card/30 py-8">
        <div className="container max-w-7xl mx-auto px-4">
          <div className="flex flex-col md:flex-row items-center justify-between gap-4">
            <div className="flex items-center gap-2">
              <BarChart3 className="w-5 h-5 text-primary" />
              <span className="font-semibold">DealFlow AI</span>
            </div>
            <p className="text-xs text-muted-foreground">
              © 2024 DealFlow AI. All rights reserved.
            </p>
          </div>
        </div>
      </footer>
    </div>
  );
}
